app_top_keyword/urls.py
from django.urls import path
from app_top_keyword import views

# declare a  namespace for this APP
# the name of namespace is  'app_top_keyword'
# We will use the namespace in the future integrated website.
app_name = 'app_top_keyword'

urlpatterns = [
    path('', views.home, name='home'),
    path('api_get_cate_topword/', views.api_get_cate_topword, name='api_cate_topword'),
]

app_top_ner/urls.py
from django.urls import path
from app_top_ner import views

app_name="app_top_ner"

urlpatterns = [
    path('', views.home, name='home'),
    path('api_get_cat_topkey/', views.api_get_cat_topkey, name='api_cat_topkey'),
]

app_user_keyword/urls.py
from django.urls import path
from app_user_keyword import views

app_name="app_user_keyword"

urlpatterns = [
    # For the user userkey analysis page
    path('', views.home, name='home'),
    path('api_get_top_userkey/', views.api_get_top_userkey),
]

app_userkey_sentiment/urls.py
from django.urls import path
from app_userkey_sentiment import views

app_name="namespace_userkey_sentiment"

urlpatterns = [
    # For the user userkey sentiment analysis page
    path('', views.home, name='home'),
    path('api_get_userkey_sentiment/', views.api_get_userkey_sentiment),
]

website_configs/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import TemplateView

urlpatterns = [
    # top keywords
    path('topword/', include('app_top_keyword.urls')),
    # top persons
    path('topperson/', include('app_top_person.urls')),
    # top name entity keyword
    path('topner/', include('app_top_ner.urls')),
    # user keyword analysis
    path('userkeyword/', include('app_user_keyword.urls')),
    # full text search and associated paragraphs for user keywords
    #path('userkeyword_assoc/', include('app_user_keyword_association.urls')),
    # user keyword sentiment analysis
    path('userkey_senti/', include('app_userkey_sentiment.urls')),

    # Sentiment analysis
    path('sentiment/', include('app_news_sentiment.urls')),

    # news classification
    path('news_cate/', include('app_news_classify.urls')),



]


templates/navbar.html

<!--<a class="navbar-brand" ></a>-->

<div class="col-lg-20 mb-3"  style="background-color: #e3f2fd;width: 100%">

    <nav class="navbar navbar-expand-lg navbar-light">
        <a class="navbar-brand" >期末專案-輿情大數據</a>
        
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">

            <ul class="navbar-nav mr-auto">

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'app_top_keyword:home' %}">熱門關鍵詞分析</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'app_top_person:home' %}">熱門人物排行分析</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'app_top_ner:home'%}">實體辨識熱門分析</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'app_user_keyword:home'%}">關鍵詞熱門度分析</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link"
                       href="{% url 'namespace_userkey_sentiment:home'%}">關鍵詞情緒分析</a>
                </li>


                <li class="nav-item">
                    <a class="nav-link" href="{% url 'namespace_news_classify:home' %}">文章分類</a>
                </li>


            </ul>

        </div>
    </nav>
</div>